import type { Feature } from '@/types/roadmap';

export const ROADMAP_DEFAULT_FEATURES: Feature[] = [
  {
    id: 'legacy-replayglowz-bookmarks',
    key: 'replayglowz-bookmarks',
    title: 'YouTube Timestamp Bookmarks',
    description: 'Save and organize bookmarks at specific video timestamps with notes',
    status: 'completed',
    projectId: 'replayglowz',
    votes: 42,
  },
  {
    id: 'legacy-replayglowz-obsidian-export',
    key: 'replayglowz-obsidian-export',
    title: 'Annotation Export to Obsidian',
    description: 'Export all video annotations directly into your Obsidian vault as structured notes',
    status: 'in-development',
    projectId: 'replayglowz',
    votes: 38,
  },
  {
    id: 'legacy-replayglowz-analytics',
    key: 'replayglowz-analytics',
    title: 'Playlist Analytics Dashboard',
    description: 'Visual overview of your watch patterns, saved content, and learning progress',
    status: 'planned',
    projectId: 'replayglowz',
    votes: 25,
  },
  {
    id: 'legacy-replayglowz-ai-summaries',
    key: 'replayglowz-ai-summaries',
    title: 'AI-Powered Video Summaries',
    description: 'Automatic chapter summaries using AI to capture key takeaways',
    status: 'considering',
    projectId: 'replayglowz',
    votes: 67,
  },
  {
    id: 'legacy-mediaflowz-rss',
    key: 'mediaflowz-rss',
    title: 'RSS Feed Aggregation',
    description: 'Unified RSS reader inside Obsidian with customizable feeds and filters',
    status: 'completed',
    projectId: 'mediaflowz',
    votes: 31,
  },
  {
    id: 'legacy-mediaflowz-scheduler',
    key: 'mediaflowz-scheduler',
    title: 'Social Media Scheduler',
    description: 'Schedule and publish content across multiple social platforms from Obsidian',
    status: 'planned',
    projectId: 'mediaflowz',
    votes: 44,
  },
  {
    id: 'legacy-mediaflowz-curation-templates',
    key: 'mediaflowz-curation-templates',
    title: 'Content Curation Templates',
    description: 'Pre-built templates for curating and organizing content from various sources',
    status: 'in-development',
    projectId: 'mediaflowz',
    votes: 19,
  },
  {
    id: 'legacy-mediaflowz-newsletter',
    key: 'mediaflowz-newsletter',
    title: 'Newsletter Generator',
    description: 'Turn curated content into formatted newsletters ready to send',
    status: 'considering',
    projectId: 'mediaflowz',
    votes: 52,
  },
  {
    id: 'legacy-winflowz-guide-v2',
    key: 'winflowz-guide-v2',
    title: 'Windows Mastery Guide v2',
    description: 'Updated guide with 200+ tips covering Windows 11 24H2 features and optimizations',
    status: 'in-development',
    projectId: 'winflowz',
    votes: 35,
  },
  {
    id: 'legacy-winflowz-plugin-manager',
    key: 'winflowz-plugin-manager',
    title: 'Plugin Manager for Obsidian',
    description: 'Search, compare, and manage Obsidian plugins with ratings and compatibility checks',
    status: 'completed',
    projectId: 'winflowz',
    votes: 28,
  },
  {
    id: 'legacy-winflowz-shortcut-trainer',
    key: 'winflowz-shortcut-trainer',
    title: 'Keyboard Shortcut Trainer',
    description: 'Interactive training mode to learn and practice Windows keyboard shortcuts',
    status: 'planned',
    projectId: 'winflowz',
    votes: 41,
  },
  {
    id: 'legacy-winflowz-workflow-builder',
    key: 'winflowz-workflow-builder',
    title: 'Workflow Automation Builder',
    description: 'Visual builder for creating custom Windows automation workflows',
    status: 'considering',
    projectId: 'winflowz',
    votes: 73,
  },
];
